### ISSUE TITLE
Error: spawn ffmpeg ENOENT for each test

### ISSUE THREAD

**Issue by ericzered** [blueimp/ffmpeg-image-diff#1]
Hello,
I'm trying to use this node in a wdio v5 project and I have an error.
I make 2 screenshot, named a.png and b.png.
Code is :

const imgDiff = require('ffmpeg-image-diff')

```
        imgDiff(
            "a.png",
            "b.png",
            "test/c.png",
            {
              ssim: true,
              similarity: 0.01, 
              blend: 1.0,
              opacity: 0.1,
              color: 'magenta'
            }
          ).then((ssim) => {
            console.log(ssim)
          }).catch((error) => {
            console.error(error)
          })

```
And I've got every time (for 2 identical images or 2 different) this error:

```
Stderr:
[0-0] { Error: spawn ffmpeg ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
     at onErrorNT (internal/child_process.js:429:16)
     at processTicksAndRejections (internal/process/task_queues.js:81:17)
   errno: 'ENOENT',
   code: 'ENOENT',
   syscall: 'spawn ffmpeg',
   path: 'ffmpeg',
   spawnargs:
    [ '-loglevel',
      'error',
      '-i',
      'a.png',
      '-i',
      'b.png',
      '-filter_complex',

'ssim=stats_file=-[ssim];[ssim][1]blend=all_mode=phoenix,format=rgba,colorkey=white:similarity=0.01:blend=1,colorbalance=rs=1:gs=-1:bs=1:rm=1:gm=-1:bm=1:rh=1:gh=-1:bh=1[diff];[0]format=rgba,colorchannelmixer=aa=0.1[b
g];[bg][diff]overlay=format=rgb',
      '-y',
      'test/c.png' ],
   cmd:
    'ffmpeg -loglevel error -i a.png -i b.png -filter_complex
ssim=stats_file=-[ssim];[ssim][1]blend=all_mode=phoenix,format=rgba,colorkey=white:similarity=0.01:blend=1,colorbalance=rs=1:gs=-1:bs=1:rm=1:gm=-1:bm=1:rh=1:gh=-1:bh=1[diff];[0]format=rgba,colorchannelmixer=aa=0.1[bg
];[bg][diff]overlay=format=rgb -y test/c.png',
   stdout: '',
   stderr: '' }
```

What can I do ? 
Thanks !

**Comment by ericzered** [comment]
Ok, I got it, I should install ffmpeg first. I was hopping only the package was enough. Sorry !

**Comment by blueimp** [comment]
No problem. ☺️ 
Maybe the wording under https://github.com/blueimp/node-ffmpeg-image-diff#requirements is a bit ambiguous.
